---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dspatiumhr/public_html/

    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp myscript.js $DEPLOYPATH
    - /bin/cp -R slike $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH